### ISSUE TITLE
Document Model

### ISSUE THREAD

**Issue by wspurgin** [wspurgin/yolo-ironman#4]
For lack of a better term, a `Document` in our system will contain all related information from indexing (and ranking after that). For now, this is the information that will be stored:

From Indexing
- [x] Document ID
- [x] URL to Document
- [x] Text from the Document (not all of it, maybe the first 20-40 words, **but pre-stemmed**)
- [x] Term Frequency "Vector"
  - Probably just a Dictionary with Terms mapped to Frequencies

From Ranking
- [x] Normalized Document "Vector"
  - Terms mapped to normalized "score"

**Comment by wspurgin** [comment]
@mooseman456 can you check off which parts of this task are done?

**Comment by mooseman456** [comment]
@wspurgin Done.

**Comment by wspurgin** [comment]
Completed as of c78f0eaa
