### ISSUE TITLE
Is it a Query or is it a Document called a Query?

### ISSUE THREAD

**Issue by wspurgin** [wspurgin/yolo-ironman#5]
A Query is (basically) the same thing as a document. It doesn't need a unique identifier, nor does it have a URL that we keep track of, but it does have words/terms and frequency and should go through the same (or similar) weighting process.

Therefore, our Query object, should basically be a document. The decision will need to be made as to whether we should actually create a sub-class Query object, or just refer to a Document object created with the query text as the "query".

**Comment by mooseman456** [comment]
@wspurgin I think I will slightly shift the Document class to have default values of None for the params that the query doesn't use (URL etc.) and just make it a Document object.
